# Generated by Django 4.1 on 2023-01-26 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bpl_app", "0006_alter_criketscores_overs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="criketscores",
            name="overs",
        ),
    ]
