# Generated by Django 4.1 on 2023-01-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpl_app", "0007_remove_criketscores_overs"),
    ]

    operations = [
        migrations.AddField(
            model_name="criketscores",
            name="overs",
            field=models.CharField(default="null", max_length=10),
        ),
    ]
