# Generated by Django 4.1 on 2023-01-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpl_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playersinfo",
            name="player_name",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="playersinfo",
            name="player_role",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
