# Generated by Django 4.1 on 2023-01-26 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bpl_app", "0008_criketscores_overs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="criketscores",
            name="overs",
        ),
    ]
